#########################################################################################################
# Author: Kennashka DeSilva
# mail@kennashka.com
# June 13, 2019
########################################################################################################

---
- hosts: addyourhost
  remote_user: ubuntu
  become: yes


  vars:
    github_email: "mail@gmail.com"
    default_file_location: "/root/.ssh/id_rsa"  # example: "enter/a/desired/file/location"
    secure_passphrase: "yourpassphrase" #Enter A Secure Passphrase Or Empty For No Passphrase
    

  tasks:
    - name: Generating public/private rsa key pair.
      expect:
        command: ssh-keygen -t rsa -b 4096 -C {{ github_email }}
        responses:
          'Enter file in which to save the key \(/home/ubuntu/.ssh/id_rsa\):': "{{ default_file_location }}"
          'Enter passphrase \(empty for no passphrase\):': "{{ secure_passphrase }}"
          'Enter same passphrase again:': "{{ secure_passphrase }}"

    - name: Start the ssh-agent in the background.
      command: eval "$(ssh-agent -s)"

    - name: Adding your SSH private key to the ssh-agent and store your passphrase in the keychain. 
      expect:
        command: ssh-add -k ~/.ssh/id_rsa
        responses:
          'Enter passphrase for .* :': "{{ secure_passphrase }}"