#########################################################################################################
# Author: Kennashka "python wizard" DeSilva 
# mail@kennashka.com
# June 13, 2019
########################################################################################################

---
- hosts: addyourhost
  remote_user: ubuntu
  become: yes


  vars:
    github_email: "mail@gmail.com"
    default_file_location: "/root/.ssh/id_rsa"  # example: "enter/a/desired/file/location"
    secure_passphrase: "yourpassphrase" #Enter A Secure Passphrase Or Empty For No Passphrase
    

  tasks:
     - name: install python pip install
       command: apt install python-pip -y

     - name: install python3 pip install
       command: apt install python3-pip -y

     - name: Install pexpect
       command: pip install pexpect

     - name: Install pexpect for python3
       command: pip3 install pexpect
      
     - name: Generating public/private rsa key pair.
       expect:
         command: ssh-keygen -t rsa -b 4096 -C {{ github_email }}
         responses:
           Enter file in which to save the key .*: "{{ default_file_location }}"
           Enter passphrase .*: "{{ secure_passphrase }}"
           Enter same passphrase .*: "{{ secure_passphrase }}"
    
     - name: Shell command please work
       shell: |
        set timeout 300
        spawn eval `ssh-agent` \n ssh-add ~/.ssh/id_rsa

        expect "Enter passphrase for .*:"
        send "{{ secure_passphrase }}\n"

        exit 0


          
#########################################################################################################
# THIS BLOCK IS FOR DEBUGGING
#    - name: enable ssh-agent
#      shell: echo "ssh-agent = $(ssh-agent)"
#########################################################################################################

